version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}occurrensapi
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
      - 5001:81
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ConnectionStrings__Default=Host=db;Port=5432;Database=occurrens;Username=postgres;Password=postgres
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    user: root
    depends_on:
      - db
  
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=occurrens
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    command: postgres -c 'listen_addresses=*'
  
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

volumes:
  pgdata:
    external: true